/*
  Chroniques d'Astréa — catalogue V11 de cartes, lieux et quêtes.
  Les cartes restent déclaratives : les effets sont interprétés par game.js.
*/

const CARDS = [
  { id:"creature_001", name:"Étincelle familière", type:"creature", cost:1, attack:1, health:2, keywords:[], effects:[], description:"Une petite présence fiable pour ouvrir la partie.", rarity:"common", tribe:"elemental", image:"assets/cards/creature_001.png" },
  { id:"creature_002", name:"Faucon de comète", type:"creature", cost:2, attack:2, health:1, keywords:["charge"], effects:[], description:"Charge.", rarity:"common", tribe:"beast", image:"assets/cards/creature_002.png" },
  { id:"creature_003", name:"Gardien des Brumes", type:"creature", cost:3, attack:2, health:5, keywords:["taunt"], effects:[], description:"Provocation.", rarity:"common", tribe:"spirit", image:"assets/cards/creature_003.png" },
  { id:"creature_004", name:"Sentinelle solaire", type:"creature", cost:3, attack:3, health:2, keywords:["divineShield"], effects:[], description:"Bouclier divin.", rarity:"rare", tribe:"construct", image:"assets/cards/creature_004.png" },
  { id:"creature_005", name:"Acolyte des runes", type:"creature", cost:2, attack:2, health:2, keywords:[], effects:[{ trigger:"battlecry", effect:"draw", target:"self", value:1 }], description:"Cri de guerre : piochez une carte.", rarity:"common", tribe:"mystic", image:"assets/cards/creature_005.png" },
  { id:"creature_006", name:"Prêtresse de l’aube", type:"creature", cost:3, attack:2, health:3, keywords:[], effects:[{ trigger:"battlecry", effect:"heal", target:"friendlyHero", value:3 }], description:"Cri de guerre : rend 3 PV à votre héros.", rarity:"common", tribe:"human", image:"assets/cards/creature_006.png" },
  { id:"creature_007", name:"Loup du crépuscule", type:"creature", cost:4, attack:4, health:4, keywords:[], effects:[], description:"Une créature équilibrée des lisières astrales.", rarity:"common", tribe:"beast", image:"assets/cards/creature_007.png" },
  { id:"creature_008", name:"Archiviste céleste", type:"creature", cost:4, attack:3, health:4, keywords:[], effects:[{ trigger:"deathrattle", effect:"draw", target:"self", value:1 }], description:"Dernier souffle : piochez une carte.", rarity:"rare", tribe:"mystic", image:"assets/cards/creature_008.png" },
  { id:"creature_009", name:"Bastion d’obsidienne", type:"creature", cost:5, attack:3, health:7, keywords:["taunt"], effects:[], description:"Provocation.", rarity:"rare", tribe:"construct", image:"assets/cards/creature_009.png" },
  { id:"creature_010", name:"Oracle de la Lune", type:"creature", cost:5, attack:4, health:5, keywords:["divineShield"], effects:[{ trigger:"battlecry", effect:"draw", target:"self", value:1 },{ trigger:"battlecry", effect:"heal", target:"friendlyHero", value:2 }], description:"Bouclier divin. Cri de guerre : piochez une carte et rendez 2 PV à votre héros.", rarity:"epic", tribe:"mystic", image:"assets/cards/creature_010.png" },
  { id:"creature_011", name:"Drake d’éther", type:"creature", cost:6, attack:6, health:5, keywords:[], effects:[], description:"Une force brute venue des courants d’éther.", rarity:"rare", tribe:"dragon", image:"assets/cards/creature_011.png" },
  { id:"creature_012", name:"Chevalier du zénith", type:"creature", cost:6, attack:5, health:6, keywords:["taunt","divineShield"], effects:[], description:"Provocation. Bouclier divin.", rarity:"epic", tribe:"human", image:"assets/cards/creature_012.png" },
  { id:"creature_013", name:"Phénix prismatique", type:"creature", cost:7, attack:7, health:5, keywords:["charge"], effects:[], description:"Charge.", rarity:"legendary", tribe:"elemental", image:"assets/cards/creature_013.png" },
  { id:"creature_014", name:"Titan des constellations", type:"creature", cost:8, attack:8, health:9, keywords:["taunt"], effects:[], description:"Provocation.", rarity:"legendary", tribe:"titan", image:"assets/cards/creature_014.png" },
  { id:"creature_015", name:"Messagère stellaire", type:"creature", cost:3, attack:3, health:3, keywords:[], effects:[{ trigger:"battlecry", effect:"buffRandomFriendly", target:"friendlyCreature", value:1 }], description:"Cri de guerre : donne +1/+1 à une autre créature alliée aléatoire.", rarity:"rare", tribe:"human", image:"assets/cards/creature_015.png" },

  { id:"spell_001", name:"Éclair astral", type:"spell", cost:2, keywords:[], effects:[{ trigger:"onPlay", effect:"damage", target:"enemyCharacter", value:3 }], description:"Inflige 3 dégâts à un personnage adverse.", rarity:"common", image:"assets/cards/spell_001.png" },
  { id:"spell_002", name:"Pluie de météores", type:"spell", cost:5, keywords:[], effects:[{ trigger:"onPlay", effect:"areaDamage", target:"allEnemyCreatures", value:2 }], description:"Inflige 2 dégâts à toutes les créatures adverses.", rarity:"rare", image:"assets/cards/spell_002.png" },
  { id:"spell_003", name:"Lueur réparatrice", type:"spell", cost:2, keywords:[], effects:[{ trigger:"onPlay", effect:"heal", target:"friendlyCharacter", value:5 }], description:"Rend 5 PV à un personnage allié.", rarity:"common", image:"assets/cards/spell_003.png" },
  { id:"spell_004", name:"Sceau de croissance", type:"spell", cost:3, keywords:[], effects:[{ trigger:"onPlay", effect:"gainMaxHealth", target:"friendlyHero", value:4 }], description:"Votre héros gagne 4 PV maximum et récupère 4 PV.", rarity:"rare", image:"assets/cards/spell_004.png" },
  { id:"spell_005", name:"Voile du silence", type:"spell", cost:2, keywords:[], effects:[{ trigger:"onPlay", effect:"silence", target:"anyCreature", value:0 }], description:"Réduit une créature au silence.", rarity:"rare", image:"assets/cards/spell_005.png" },
  { id:"spell_006", name:"Vision cosmique", type:"spell", cost:3, keywords:[], effects:[{ trigger:"onPlay", effect:"draw", target:"self", value:2 }], description:"Piochez 2 cartes.", rarity:"common", image:"assets/cards/spell_006.png" },
  { id:"spell_007", name:"Bénédiction sidérale", type:"spell", cost:3, keywords:[], effects:[{ trigger:"onPlay", effect:"buff", target:"friendlyCreature", value:2 }], description:"Donne +2/+2 à une créature alliée.", rarity:"rare", image:"assets/cards/spell_007.png" },
  { id:"spell_008", name:"Nova du vide", type:"spell", cost:7, keywords:[], effects:[{ trigger:"onPlay", effect:"areaDamage", target:"allCreatures", value:4 }], description:"Inflige 4 dégâts à toutes les créatures.", rarity:"epic", image:"assets/cards/spell_008.png" },
  { id:"spell_009", name:"Rayon de rupture", type:"spell", cost:4, keywords:[], effects:[{ trigger:"onPlay", effect:"damage", target:"enemyCreature", value:6 }], description:"Inflige 6 dégâts à une créature adverse.", rarity:"epic", image:"assets/cards/spell_009.png" },

  /* Armes et nouvelles mécaniques */
  { id:"weapon_001", name:"Lame de l’aurore", type:"weapon", cost:4, attack:4, durability:2, keywords:[], effects:[{ trigger:"afterHeroAttack", effect:"heal", target:"friendlyHero", value:2 }], description:"Après que votre héros a attaqué, rendez-lui 2 PV.", rarity:"rare", image:"assets/cards/weapon_001.png" },
  { id:"weapon_002", name:"Sceptre du firmament", type:"weapon", cost:3, attack:2, durability:3, keywords:[], effects:[{ trigger:"afterHeroAttack", effect:"randomDamage", target:"randomEnemyCharacter", value:1, count:1 }], description:"Après que votre héros a attaqué, inflige 1 dégât à un ennemi aléatoire.", rarity:"epic", image:"assets/cards/weapon_002.jpg" },

  { id:"secret_001", name:"Barrière de nébuleuse", type:"secret", cost:2, secretTrigger:"beforeHeroAttacked", keywords:[], effects:[{ trigger:"secret", effect:"armor", target:"friendlyHero", value:6 }], description:"Secret : lorsqu’un ennemi attaque votre héros, gagnez 6 Armure.", rarity:"rare", image:"assets/cards/secret_001.jpg" },
  { id:"secret_002", name:"Reflet stellaire", type:"secret", cost:3, secretTrigger:"afterEnemyPlaysCreature", keywords:[], effects:[{ trigger:"secret", effect:"summonCopyFromContext", target:"friendlyBoard", attack:1, health:1 }], description:"Secret : après que l’adversaire joue une créature, invoquez-en une copie 1/1.", rarity:"epic", image:"assets/cards/secret_002.jpg" },
  { id:"secret_003", name:"Contresort astral", type:"secret", cost:3, secretTrigger:"beforeEnemySpell", keywords:[], effects:[{ trigger:"secret", effect:"counterSpell", target:"context", value:1 }], description:"Secret : lorsque l’adversaire lance un sort, contrez-le.", rarity:"epic", image:"assets/cards/secret_003.jpg" },

  { id:"spell_010", name:"Convergence astrale", type:"spell", cost:3, keywords:[], choices:[
      { id:"draw", label:"Lire les étoiles", description:"Piochez 2 cartes.", effects:[{ trigger:"onPlay", effect:"draw", target:"self", value:2 }] },
      { id:"armor", label:"Sceller le destin", description:"Gagnez 6 Armure.", effects:[{ trigger:"onPlay", effect:"armor", target:"friendlyHero", value:6 }] }
    ], effects:[], description:"Choix : piochez 2 cartes ou gagnez 6 Armure.", rarity:"rare", image:"assets/cards/spell_010.jpg" },
  { id:"spell_011", name:"Métamorphose stellaire", type:"spell", cost:4, keywords:[], effects:[{ trigger:"onPlay", effect:"transform", target:"anyCreature", cardId:"token_001" }], description:"Transforme une créature en Agneau astral 1/1.", rarity:"epic", image:"assets/cards/spell_011.jpg" },
  { id:"spell_012", name:"Cascade cosmique", type:"spell", cost:5, keywords:[], effects:[{ trigger:"onPlay", effect:"randomDamage", target:"randomEnemyCharacter", value:2, count:3 }], description:"Inflige 2 dégâts à un ennemi aléatoire, trois fois.", rarity:"epic", image:"assets/cards/spell_012.jpg" },
  { id:"spell_013", name:"Portail du zénith", type:"spell", cost:6, keywords:[], effects:[{ trigger:"onPlay", effect:"summon", target:"friendlyBoard", cardId:"token_002", count:2 },{ trigger:"onPlay", effect:"heal", target:"friendlyHero", value:4 }], description:"Invoque deux Fragments d’étoile 2/2 et rend 4 PV à votre héros.", rarity:"legendary", image:"assets/cards/spell_013.jpg" },

  { id:"creature_016", name:"Chronomancienne runique", type:"creature", cost:4, attack:3, health:4, keywords:[], effects:[{ trigger:"battlecry", effect:"reduceRandomHandCost", target:"friendlyHand", value:2 }], description:"Cri de guerre : réduit de (2) le coût d’une carte aléatoire de votre main.", rarity:"epic", tribe:"mystic", image:"assets/cards/creature_016.jpg" },
  { id:"creature_017", name:"Tisseuse de réalités", type:"creature", cost:6, attack:5, health:5, keywords:[], effects:[{ trigger:"deathrattle", effect:"summon", target:"friendlyBoard", cardId:"token_002", count:2 }], description:"Dernier souffle : invoque deux Fragments d’étoile 2/2.", rarity:"epic", tribe:"mystic", image:"assets/cards/creature_017.jpg" },
  { id:"creature_018", name:"Astrael, Porte-aube", type:"creature", cost:8, attack:5, health:8, keywords:["taunt","divineShield"], effects:[{ trigger:"battlecry", effect:"buffAllFriendly", target:"allFriendlyCreatures", value:2, excludeSelf:true }], description:"Provocation. Bouclier divin. Cri de guerre : donne +2/+2 à vos autres créatures.", rarity:"legendary", tribe:"human", image:"assets/cards/creature_018.png" },


  /* Quêtes du Firmament */
  { id:"quest_001", name:"Sentier des étoiles", type:"quest", cost:1, keywords:[], quest:{ event:"spellPlayed", goal:5, reward:[{ effect:"draw", target:"self", value:3 }] }, effects:[], description:"Quête : jouez 5 sorts. Récompense : piochez 3 cartes.", rarity:"legendary", image:"assets/cards/quest_001.png" },
  { id:"quest_002", name:"Épreuve du zénith", type:"quest", cost:1, keywords:[], quest:{ event:"creatureSummoned", goal:6, reward:[{ effect:"buffAllFriendly", target:"allFriendlyCreatures", value:2 }] }, effects:[], description:"Quête : invoquez 6 créatures. Récompense : donne +2/+2 à vos créatures.", rarity:"legendary", image:"assets/cards/quest_002.png" },
  { id:"quest_003", name:"Veille du sanctuaire", type:"quest", cost:1, keywords:[], quest:{ event:"healingDone", goal:12, reward:[{ effect:"armor", target:"friendlyHero", value:8 }] }, effects:[], description:"Quête : rendez 12 PV. Récompense : votre héros gagne 8 Armure.", rarity:"legendary", image:"assets/cards/quest_003.png" },

  /* Nouvelles cartes illustrées */
  { id:"creature_019", name:"Gardienne du firmament", type:"creature", cost:4, attack:4, health:5, keywords:[], effects:[{ trigger:"battlecry", effect:"summon", target:"friendlyBoard", cardId:"creature_001", count:1 }], description:"Cri de guerre : invoque une Étincelle familière 1/2.", rarity:"rare", tribe:"human", image:"assets/cards/creature_019.png" },
  { id:"weapon_003", name:"Marteau de l’aurore", type:"weapon", cost:3, attack:3, durability:2, keywords:[], effects:[{ trigger:"afterHeroAttack", effect:"heal", target:"friendlyHero", value:1 }], description:"Après que votre héros a attaqué, rendez-lui 1 PV.", rarity:"rare", image:"assets/cards/weapon_003.png" },
  { id:"spell_014", name:"Portail astral", type:"spell", cost:4, keywords:[], effects:[{ trigger:"onPlay", effect:"summon", target:"friendlyBoard", cardId:"creature_001", count:2 }], description:"Invoque deux Étincelles familières 1/2.", rarity:"rare", image:"assets/cards/spell_014.png" },

  { id:"creature_020", name:"Apprentie astromancienne", type:"creature", cost:2, attack:2, health:2, keywords:[], effects:[{ trigger:"battlecry", effect:"discountSpellsInHand", target:"friendlyHand", value:1 }], description:"Cri de guerre : les sorts de votre main coûtent (1) de moins.", rarity:"common", tribe:"human", image:"assets/cards/creature_020.png" },
  { id:"creature_021", name:"Loup spectral", type:"creature", cost:2, attack:2, health:2, keywords:[], effects:[{ trigger:"deathrattle", effect:"addCardToHand", target:"friendlyHand", cardId:"token_003", count:1 }], description:"Dernier souffle : ajoute un Loup spectral 1/1 dans votre main.", rarity:"common", tribe:"beast", image:"assets/cards/creature_021.png" },
  { id:"creature_022", name:"Guerrier stellaire", type:"creature", cost:3, attack:2, health:4, keywords:["taunt"], effects:[{ trigger:"afterDamaged", effect:"buffSelfOnce", attack:2, health:2 }], description:"Provocation. La première fois qu’il survit à des dégâts, gagne +2/+2.", rarity:"rare", tribe:"human", image:"assets/cards/creature_022.png" },
  { id:"spell_015", name:"Échos du néant", type:"spell", cost:3, keywords:[], effects:[{ trigger:"onPlay", effect:"damage", target:"enemyCharacter", value:3 },{ trigger:"onPlay", effect:"discoverRandom", target:"friendlyHand", cardIds:["spell_001","spell_005","spell_006"] }], description:"Inflige 3 dégâts. Ajoute un sort astral aléatoire dans votre main.", rarity:"rare", image:"assets/cards/spell_015.png" },
  { id:"creature_023", name:"Sentinelle d’Astréa", type:"creature", cost:4, attack:3, health:5, keywords:["divineShield"], effects:[{ trigger:"allyHealed", effect:"gainAttack", value:1 }], description:"Bouclier divin. Quand un autre allié est soigné, gagne +1 ATQ.", rarity:"epic", tribe:"dragon", image:"assets/cards/creature_023.png" },
  { id:"creature_024", name:"Ancien protecteur", type:"creature", cost:4, attack:1, health:6, keywords:[], effects:[{ trigger:"battlecry", effect:"buffSelfPerFriendly", value:1 }], description:"Cri de guerre : gagne +1/+1 pour chaque autre créature alliée.", rarity:"epic", tribe:"elemental", image:"assets/cards/creature_024.png" },
  { id:"creature_025", name:"Oracle des étoiles", type:"creature", cost:5, attack:3, health:3, keywords:[], effects:[{ trigger:"battlecry", effect:"drawFromTopThree" }], description:"Cri de guerre : regarde les 3 prochaines cartes de votre deck et place la plus coûteuse dans votre main.", rarity:"legendary", tribe:"human", image:"assets/cards/creature_025.png" },
  { id:"spell_016", name:"Cœur de comète", type:"spell", cost:5, keywords:[], effects:[{ trigger:"onPlay", effect:"randomDamage", target:"randomEnemyMinion", value:1, count:5 }], description:"Inflige 5 dégâts répartis aléatoirement entre les créatures adverses.", rarity:"rare", image:"assets/cards/spell_016.png" },
  { id:"creature_026", name:"Léviathan stellaire", type:"creature", cost:6, attack:5, health:7, keywords:[], effects:[{ trigger:"battlecry", effect:"devourBoard" },{ trigger:"deathrattle", effect:"resurrectFromSource", count:3 }], description:"Cri de guerre : détruit les autres créatures. Dernier souffle : en ressuscite jusqu’à 3 sous votre contrôle.", rarity:"legendary", tribe:"dragon", image:"assets/cards/creature_026.png" },
  { id:"spell_017", name:"Portail cosmique", type:"spell", cost:7, keywords:[], effects:[{ trigger:"onPlay", effect:"summonRandomHighCostAndAttack", count:2, minCost:5 }], description:"Invoque deux créatures aléatoires coûtant au moins (5). Elles attaquent une créature adverse aléatoire.", rarity:"epic", image:"assets/cards/spell_017.png" },


  /* Sorts ajoutés depuis les cartes fournies par l’utilisateur */
  { id:"spell_018", name:"Éruption astrale", type:"spell", cost:1, keywords:[], effects:[{ trigger:"onPlay", effect:"damage", target:"enemyCharacter", value:2 }], description:"Inflige 2 dégâts.", rarity:"common", image:"assets/cards/spell_018.png" },
  { id:"spell_019", name:"Soin des constellations", type:"spell", cost:2, keywords:[], effects:[{ trigger:"onPlay", effect:"heal", target:"friendlyHero", value:4 }], description:"Rend 4 PV à votre héros.", rarity:"common", image:"assets/cards/spell_019.png" },
  { id:"spell_020", name:"Nova de givre sidéral", type:"spell", cost:3, keywords:[], effects:[{ trigger:"onPlay", effect:"areaDamage", target:"allEnemyCreatures", value:1 }], description:"Inflige 1 dégât à tous les serviteurs ennemis.", rarity:"rare", image:"assets/cards/spell_020.png" },
  { id:"spell_021", name:"Portée stellaire", type:"spell", cost:2, keywords:[], effects:[{ trigger:"onPlay", effect:"draw", target:"self", value:2 }], description:"Pioche 2 cartes.", rarity:"epic", image:"assets/cards/spell_021.png" },
  { id:"spell_022", name:"Bénédiction du zénith", type:"spell", cost:4, keywords:[], effects:[{ trigger:"onPlay", effect:"buff", target:"friendlyCreature", value:2 }], description:"Donne +2/+2 à un serviteur allié.", rarity:"rare", image:"assets/cards/spell_022.png" },
  { id:"spell_023", name:"Faille du néant", type:"spell", cost:5, keywords:[], effects:[{ trigger:"onPlay", effect:"destroyIfDamaged", target:"damagedCreature", value:0 }], description:"Détruit un serviteur blessé.", rarity:"epic", image:"assets/cards/spell_023.png" },
  { id:"spell_024", name:"Comète jumelle", type:"spell", cost:4, keywords:[], effects:[{ trigger:"onPlay", effect:"randomDamage", target:"randomEnemyCharacter", value:1, count:3 }], description:"Inflige 3 dégâts répartis aléatoirement entre les ennemis.", rarity:"common", image:"assets/cards/spell_024.png" },
  { id:"spell_025", name:"Écho du firmament", type:"spell", cost:3, keywords:[], effects:[{ trigger:"onPlay", effect:"nextSpellDiscount", target:"self", value:2 }], description:"Votre prochain sort coûte (2) de moins.", rarity:"rare", image:"assets/cards/spell_025.png" },
  { id:"spell_026", name:"Métamorphose lunaire", type:"spell", cost:4, keywords:[], effects:[{ trigger:"onPlay", effect:"transform", target:"anyCreature", cardId:"token_001" }], description:"Transforme un serviteur en Agneau astral 1/1.", rarity:"epic", image:"assets/cards/spell_026.png" },
  { id:"spell_027", name:"Apothéose d’Astréa", type:"spell", cost:7, keywords:[], effects:[{ trigger:"onPlay", effect:"areaDamage", target:"allEnemies", value:5 }], description:"Inflige 5 dégâts à tous les ennemis.", rarity:"legendary", image:"assets/cards/spell_027.png" },


  /* Cartes communes du pack cards.zip */
  { id:"spell_028", name:"Éclat de guérison", type:"spell", cost:1, keywords:[], effects:[{ trigger:"onPlay", effect:"heal", target:"friendlyCreature", value:3 },{ trigger:"onPlay", effect:"draw", target:"self", value:1 }], description:"Rend 3 PV à un serviteur allié. Piochez une carte.", rarity:"common", image:"assets/cards/spell_028.png" },
  { id:"creature_027", name:"Rongeur des catacombes", type:"creature", cost:1, attack:1, health:1, keywords:["windfury","immuneOpponentTurn"], effects:[], description:"Furie des vents. Insensible pendant le tour adverse.", rarity:"common", tribe:"beast", image:"assets/cards/creature_027.png" },
  { id:"spell_029", name:"Posture défensive", type:"spell", cost:2, keywords:[], effects:[{ trigger:"onPlay", effect:"armor", target:"friendlyHero", value:2 },{ trigger:"onPlay", effect:"draw", target:"self", value:1 }], description:"Confère 2 Armure à votre héros. Piochez une carte.", rarity:"common", image:"assets/cards/spell_029.png" },
  { id:"creature_028", name:"Imp espiègle", type:"creature", cost:2, attack:3, health:2, keywords:[], effects:[{ trigger:"battlecry", effect:"damage", target:"enemyHero", value:2 }], description:"Cri de guerre : inflige 2 dégâts au héros adverse.", rarity:"common", tribe:"demon", image:"assets/cards/creature_028.png" },
  { id:"spell_030", name:"Élixir revigorant", type:"spell", cost:2, keywords:[], effects:[{ trigger:"onPlay", effect:"heal", target:"friendlyHero", value:4 }], description:"Rend 4 PV à votre héros.", rarity:"common", image:"assets/cards/spell_030.png" },
  { id:"creature_029", name:"Archer de sentinelle", type:"creature", cost:3, attack:3, health:2, keywords:[], effects:[{ trigger:"battlecry", effect:"randomDamageConditionalStealth", target:"randomEnemyCharacter", value:1 }], description:"Cri de guerre : inflige 1 dégât à un ennemi aléatoire. Si c’est un serviteur, gagne Camouflage.", rarity:"common", tribe:"human", image:"assets/cards/creature_029.png" },
  { id:"spell_031", name:"Sceau de clairvoyance", type:"spell", cost:3, keywords:[], effects:[{ trigger:"onPlay", effect:"discoverAnyCardDiscountSpell", target:"self", value:1 }], description:"Découvrez une carte. Si c’est un sort, réduisez son coût de (1).", rarity:"common", image:"assets/cards/spell_031.png" },
  { id:"creature_030", name:"Chevalier du Soleil", type:"creature", cost:4, attack:3, health:5, keywords:["divineShield"], effects:[{ trigger:"afterAttack", effect:"heal", target:"friendlyHero", value:2 }], description:"Bouclier divin. Après que ce serviteur attaque, rend 2 PV à votre héros.", rarity:"common", tribe:"human", image:"assets/cards/creature_030.png" },
  { id:"spell_032", name:"Rempart de bois", type:"spell", cost:4, keywords:[], effects:[{ trigger:"onPlay", effect:"buffStatsAndKeyword", target:"friendlyCreature", attack:0, health:2, keyword:"taunt" }], description:"Confère Provocation à un serviteur allié. Il gagne +2 PV.", rarity:"common", image:"assets/cards/spell_032.png" },
  { id:"creature_031", name:"Griffon des plaines", type:"creature", cost:5, attack:4, health:4, keywords:[], effects:[{ trigger:"battlecry", effect:"draw", target:"self", value:1 }], description:"Cri de guerre : piochez une carte.", rarity:"common", tribe:"beast", image:"assets/cards/creature_031.png" },

  /* Cartes individuelles supplémentaires du pack */
  { id:"location_001", name:"Grand sanctuaire", type:"location", cost:2, durability:3, keywords:[], effects:[{ trigger:"startOfTurn", effect:"heal", target:"friendlyHero", value:2 }], description:"Au début de votre tour, rend 2 PV à votre héros. 3 utilisations.", rarity:"rare", image:"assets/cards/location_001.png" },
  { id:"spell_033", name:"Main d’Astréa", type:"spell", cost:2, keywords:[], effects:[{ trigger:"onPlay", effect:"buffStats", target:"friendlyCreature", attack:2, health:1 },{ trigger:"onPlay", effect:"draw", target:"self", value:1 }], description:"Donne +2/+1 à un serviteur allié. Piochez une carte.", rarity:"rare", image:"assets/cards/spell_033.png" },
  { id:"creature_032", name:"Gardien runique", type:"creature", cost:3, attack:3, health:4, keywords:["divineShield"], effects:[], description:"Bouclier divin.", rarity:"rare", tribe:"construct", image:"assets/cards/creature_032.png" },

  /* Dix cartes légendaires */
  { id:"creature_033", name:"Astraéa, Reine des Constellations", type:"creature", cost:8, attack:7, health:7, keywords:[], effects:[{ trigger:"battlecry", effect:"areaDamage", target:"allEnemies", value:3 }], description:"Cri de guerre : inflige 3 dégâts à tous les ennemis.", rarity:"legendary", tribe:"human", image:"assets/cards/creature_033.png" },
  { id:"creature_034", name:"Elyndra Porte-Aube", type:"creature", cost:6, attack:4, health:8, keywords:["divineShield"], effects:[{ trigger:"aura", effect:"spellCostAura", value:1 }], description:"Bouclier divin. Vos sorts coûtent (1) de moins.", rarity:"legendary", tribe:"human", image:"assets/cards/creature_034.png" },
  { id:"creature_035", name:"Vorakel, Seigneur du Néant", type:"creature", cost:9, attack:8, health:8, keywords:[], effects:[{ trigger:"endOfTurn", effect:"destroyDamagedEnemy" }], description:"À la fin de votre tour, détruit un serviteur adverse blessé.", rarity:"legendary", tribe:"mystic", image:"assets/cards/creature_035.png" },
  { id:"creature_036", name:"Lyra, Oracle des Lunes", type:"creature", cost:5, attack:3, health:6, keywords:[], effects:[{ trigger:"afterOwnerSpellPlayed", effect:"buffSelf", attack:1, health:1 }], description:"Chaque fois que vous lancez un sort, gagne +1/+1.", rarity:"legendary", tribe:"mystic", image:"assets/cards/creature_036.png" },
  { id:"creature_037", name:"Solkar, Titan du Zénith", type:"creature", cost:10, attack:10, health:10, keywords:["taunt"], effects:[{ trigger:"battlecry", effect:"buffAllFriendly", target:"allFriendlyCreatures", value:2, excludeSelf:true }], description:"Provocation. Cri de guerre : donne +2/+2 à vos autres serviteurs.", rarity:"legendary", tribe:"titan", image:"assets/cards/creature_037.png" },
  { id:"creature_038", name:"Phénix de l’Aube Éternelle", type:"creature", cost:7, attack:6, health:5, keywords:[], effects:[{ trigger:"deathrattle", effect:"reincarnateSource", health:1 }], description:"Râle d’agonie : revient à la vie avec 1 PV.", rarity:"legendary", tribe:"elemental", image:"assets/cards/creature_038.png" },
  { id:"weapon_004", name:"Marteau du Zénith", type:"weapon", cost:5, attack:4, durability:2, keywords:[], effects:[{ trigger:"afterHeroAttack", effect:"randomDamage", target:"randomEnemyCharacter", value:2, count:1 }], description:"Après l’attaque de votre héros, inflige 2 dégâts à un ennemi aléatoire.", rarity:"legendary", image:"assets/cards/weapon_004.png" },
  { id:"spell_034", name:"Couronnement Astral", type:"spell", cost:7, keywords:[], effects:[{ trigger:"onPlay", effect:"buffAllFriendly", target:"allFriendlyCreatures", value:3 }], description:"Donne +3/+3 à tous vos serviteurs.", rarity:"legendary", image:"assets/cards/spell_034.png" },
  { id:"spell_035", name:"Dévoreur d’Étoiles", type:"spell", cost:8, keywords:[], effects:[{ trigger:"onPlay", effect:"destroyAndSummonCopy", target:"anyCreature", attack:5, health:5 }], description:"Détruit un serviteur. Invoque une copie 5/5 pour vous.", rarity:"legendary", image:"assets/cards/spell_035.png" },
  { id:"spell_036", name:"Chant des Mondes", type:"spell", cost:6, keywords:[], effects:[{ trigger:"onPlay", effect:"draw", target:"self", value:3 },{ trigger:"onPlay", effect:"heal", target:"friendlyHero", value:3 }], description:"Piochez 3 cartes. Rend 3 PV à votre héros.", rarity:"legendary", image:"assets/cards/spell_036.png" },

  /* Cartes spéciales ajoutées ensuite */
  { id:"creature_039", name:"Aion, Colosse du Firmament", type:"creature", cost:18, attack:16, health:20, keywords:["taunt","divineShield"], dormantTurns:4, dynamicCost:"cardsPlayed", effects:[{ trigger:"deathrattle", effect:"fillBoardRandomLowCost", maxCost:3 }], description:"Provocation. Bouclier divin. En sommeil pendant 4 tours. Coûte (1) de moins par carte jouée durant la partie. Râle d’agonie : remplit votre plateau de serviteurs aléatoires coûtant (3) ou moins.", rarity:"legendary", tribe:"titan", image:"assets/cards/creature_039.png" },
  { id:"creature_040", name:"Séraphine, Gardienne éternelle", type:"creature", cost:6, attack:1, health:8, keywords:["divineShield"], effects:[{ trigger:"battlecry", effect:"grantReincarnation", target:"friendlyCreature" },{ trigger:"afterAnyCardPlayed", effect:"buffSelf", attack:1, health:2 },{ trigger:"deathrattle", effect:"damageOwnHero", value:3 }], description:"Bouclier divin. Cri de guerre : confère Réincarnation à un serviteur allié. Chaque fois qu’une carte est jouée, gagne +1/+2. Râle d’agonie : inflige 3 dégâts à votre héros.", rarity:"legendary", tribe:"spirit", image:"assets/cards/creature_040.png" },
  { id:"spell_037", name:"Arène du dernier survivant", type:"spell", cost:10, marginalDiscount:5, keywords:["marginal"], effects:[{ trigger:"onPlay", effect:"arenaLastSurvivor" }], description:"Les serviteurs adverses se combattent : un seul survit. Si l’adversaire en contrôle exactement 3, volez-les. Marginal : coûte (5) de moins.", rarity:"epic", image:"assets/cards/spell_037.png" },

  /* Pack de 40 cartes intégré depuis cards.zip */
  { id:"creature_041", name:"Inquisiteur du Voile", type:"creature", cost:3, attack:3, health:2, keywords:[], effects:[{ trigger:"battlecry", effect:"silence", target:"anyCreature" }], description:"Cri de guerre : réduit au silence un serviteur.", rarity:"epic", tribe:"human", image:"assets/cards/creature_041.png" },
  { id:"creature_042", name:"Sanglier météore", type:"creature", cost:2, attack:2, health:1, keywords:["charge"], effects:[], description:"Charge.", rarity:"rare", tribe:"beast", image:"assets/cards/creature_042.png" },
  { id:"creature_043", name:"Traqueuse du zénith", type:"creature", cost:4, attack:4, health:3, keywords:["rush"], effects:[{ trigger:"afterAttack", effect:"buffSelfAfterAttackingMinion", attack:1, health:1 }], description:"Ruée. Après avoir attaqué un serviteur, gagne +1/+1.", rarity:"epic", tribe:"human", image:"assets/cards/creature_043.png" },
  { id:"creature_044", name:"Gardien sépulcral astral", type:"creature", cost:5, attack:3, health:6, keywords:["taunt"], effects:[{ trigger:"deathrattle", effect:"summon", target:"friendlyBoard", cardId:"token_003", count:2 }], description:"Provocation. Râle d’agonie : invoque deux Esprits 1/1.", rarity:"rare", tribe:"spirit", image:"assets/cards/creature_044.png" },
  { id:"creature_045", name:"Archiviste des échos", type:"creature", cost:4, attack:2, health:5, keywords:[], effects:[{ trigger:"battlecry", effect:"silenceAndBuff", target:"friendlyCreature", attack:2, health:2 }], description:"Cri de guerre : réduit au silence un serviteur allié, puis lui donne +2/+2.", rarity:"rare", tribe:"mystic", image:"assets/cards/creature_045.png" },
  { id:"creature_046", name:"Drake de l’impact stellaire", type:"creature", cost:6, attack:6, health:5, keywords:["charge"], effects:[{ trigger:"deathrattle", effect:"damageBothHeroes", value:2 }], description:"Charge. Râle d’agonie : inflige 2 dégâts aux deux héros.", rarity:"rare", tribe:"dragon", image:"assets/cards/creature_046.png" },
  { id:"creature_047", name:"Faucheuse du néant paisible", type:"creature", cost:7, attack:5, health:5, keywords:["rush"], effects:[{ trigger:"deathrattle", effect:"destroyRandomDamagedMinion" }], description:"Ruée. Râle d’agonie : détruit un serviteur blessé aléatoire.", rarity:"epic", tribe:"mystic", image:"assets/cards/creature_047.png" },
  { id:"creature_048", name:"Agneau de la lune brisée", type:"creature", cost:1, attack:1, health:1, keywords:[], effects:[{ trigger:"deathrattle", effect:"heal", target:"friendlyHero", value:2 }], description:"Râle d’agonie : rend 2 PV à votre héros.", rarity:"epic", tribe:"beast", image:"assets/cards/creature_048.png" },
  { id:"creature_049", name:"Championne cométaire", type:"creature", cost:5, attack:5, health:4, keywords:["rush","divineShield"], effects:[], description:"Ruée. Bouclier divin.", rarity:"common", tribe:"human", image:"assets/cards/creature_049.png" },
  { id:"creature_050", name:"Colosse du silence éternel", type:"creature", cost:8, attack:7, health:8, keywords:["taunt"], effects:[{ trigger:"aura", effect:"damagedMinionsCannotAttack" }], description:"Provocation. Les serviteurs blessés ne peuvent pas attaquer.", rarity:"epic", tribe:"construct", image:"assets/cards/creature_050.png" },

  { id:"spell_038", name:"Sort des constellations glacées", type:"spell", cost:2, keywords:[], effects:[{ trigger:"onPlay", effect:"freeze", target:"anyCreature" }], description:"Gèle un serviteur.", rarity:"rare", image:"assets/cards/spell_038.png" },
  { id:"creature_051", name:"Gardien du Givre Astral", type:"creature", cost:4, attack:3, health:6, keywords:["taunt"], effects:[{ trigger:"battlecry", effect:"freeze", target:"enemyCreature" }], description:"Provocation. Cri de guerre : gèle un serviteur ennemi.", rarity:"rare", tribe:"construct", image:"assets/cards/creature_051.png" },
  { id:"spell_039", name:"Volonté usurpée", type:"spell", cost:5, keywords:[], effects:[{ trigger:"onPlay", effect:"temporaryControl", target:"enemyCreature" }], description:"Prenez le contrôle d’un serviteur adverse jusqu’à la fin du tour. Il gagne Charge.", rarity:"epic", image:"assets/cards/spell_039.png" },
  { id:"spell_040", name:"Mêlée chaotique", type:"spell", cost:4, keywords:[], effects:[{ trigger:"onPlay", effect:"forceAllMinionsAttackRandom" }], description:"Tous les serviteurs attaquent un serviteur aléatoire.", rarity:"rare", image:"assets/cards/spell_040.png" },
  { id:"spell_041", name:"Mirage de discorde", type:"spell", cost:3, keywords:[], effects:[{ trigger:"onPlay", effect:"forceTargetAttackRandomAlly", target:"enemyCreature" }], description:"Choisissez un serviteur adverse. Il attaque un serviteur allié aléatoire.", rarity:"rare", image:"assets/cards/spell_041.png" },
  { id:"spell_042", name:"Tempête de stase", type:"spell", cost:6, keywords:[], effects:[{ trigger:"onPlay", effect:"freezeAllEnemyMinions" }], description:"Gèle tous les serviteurs ennemis.", rarity:"rare", image:"assets/cards/spell_042.png" },
  { id:"creature_052", name:"Marionnettiste du Néant", type:"creature", cost:5, attack:4, health:5, keywords:[], effects:[{ trigger:"battlecry", effect:"temporaryControl", target:"enemyCreature" }], description:"Cri de guerre : prenez le contrôle d’un serviteur adverse jusqu’à la fin du tour.", rarity:"epic", tribe:"mystic", image:"assets/cards/creature_052.png" },
  { id:"creature_053", name:"Arbitre cosmique du champ de bataille", type:"creature", cost:7, attack:5, health:8, keywords:[], effects:[{ trigger:"battlecry", effect:"forceAllOtherMinionsAttackRandom" }], description:"Cri de guerre : force tous les autres serviteurs à attaquer un serviteur aléatoire.", rarity:"rare", tribe:"mystic", image:"assets/cards/creature_053.png" },
  { id:"creature_054", name:"Sorcière lunaire", type:"creature", cost:3, attack:2, health:4, keywords:[], effects:[{ trigger:"afterOwnerSpellPlayed", effect:"freezeRandomEnemy" }], description:"Chaque fois que vous lancez un sort, gèle un serviteur ennemi aléatoire.", rarity:"rare", tribe:"mystic", image:"assets/cards/creature_054.png" },
  { id:"spell_043", name:"Trou du néant", type:"spell", cost:6, keywords:[], effects:[{ trigger:"onPlay", effect:"forceAllMinionsAttackRandom", effect:"freezeAllEnymyMinions", effect:"transform", target:"enemyCreature", cardId:"token_001"}], description:"Force les ennemies à attaquer de façon aléatoire, les gèles, puis transforme en agneau astral 1/1.", rarity:"legendary", image:"assets/cards/spell_043.png" },

  { id:"weapon_005", name:"Dague céleste des éclats étoilés", type:"weapon", cost:2, attack:1, durability:2, keywords:[], effects:[{ trigger:"onPlay", effect:"damage", target:"enemyCharacter", value:1 }], description:"Cri de guerre : inflige 1 dégât.", rarity:"rare", image:"assets/cards/weapon_005.png" },
  { id:"weapon_006", name:"Lance du croissant lunaire", type:"weapon", cost:3, attack:2, durability:3, keywords:[], effects:[{ trigger:"afterHeroAttack", effect:"gainWeaponAttackThisTurn", value:1 }], description:"Après que votre héros attaque, gagne +1 ATQ ce tour-ci.", rarity:"rare", image:"assets/cards/weapon_006.png" },
  { id:"weapon_007", name:"Arc des comètes jumelles", type:"weapon", cost:4, attack:3, durability:2, keywords:["heroRush"], effects:[], description:"Votre héros peut attaquer les serviteurs immédiatement.", rarity:"rare", image:"assets/cards/weapon_007.png" },
  { id:"weapon_008", name:"Bouclier tranchant astral", type:"weapon", cost:4, attack:1, durability:5, keywords:["taunt"], effects:[{ trigger:"afterHeroAttack", effect:"gainWeaponDurability", value:1 }], description:"Provocation. Après l’attaque de votre héros, gagne +1 Durabilité.", rarity:"rare", image:"assets/cards/weapon_008.png" },
  { id:"weapon_009", name:"Faux du néant affamé", type:"weapon", cost:5, attack:3, durability:4, keywords:["lifesteal"], effects:[{ trigger:"afterHeroAttack", effect:"gainWeaponAttackThisTurn", value:1 }], description:"Vol de vie. Chaque fois que votre héros attaque, il gagne +1 ATQ ce tour-ci.", rarity:"epic", image:"assets/cards/weapon_009.png" },
  { id:"weapon_010", name:"Sceptre-lame des constellations", type:"weapon", cost:5, attack:3, durability:3, keywords:[], effects:[{ trigger:"onPlay", effect:"draw", target:"self", value:1 }], description:"Cri de guerre : pioche une carte.", rarity:"rare", image:"assets/cards/weapon_010.png" },
  { id:"weapon_011", name:"Marteau du zénith magique", type:"weapon", cost:6, attack:4, durability:3, keywords:[], effects:[{ trigger:"afterHeroAttack", effect:"buffRandomFriendly", value:1 }], description:"Après l’attaque de votre héros, donne +1/+1 à un serviteur allié.", rarity:"rare", image:"assets/cards/weapon_011.png" },
  { id:"weapon_012", name:"Rapière du dernier éclat", type:"weapon", cost:6, attack:3, durability:2, keywords:["windfury"], effects:[], description:"Furie des vents.", rarity:"rare", image:"assets/cards/weapon_012.png" },
  { id:"weapon_013", name:"Trident de l’aube éternelle", type:"weapon", cost:7, attack:5, durability:2, keywords:["heroDivineShield"], effects:[], description:"Bouclier divin. Perd ce Bouclier après la première attaque de votre héros.", rarity:"rare", image:"assets/cards/weapon_013.png" },
  { id:"weapon_014", name:"Hache des cataclysmes", type:"weapon", cost:8, attack:5, durability:4, keywords:[], effects:[{ trigger:"afterHeroAttack", effect:"damageAllOtherMinions", value:1 }], description:"À chaque attaque, inflige 1 dégât à tous les autres serviteurs.", rarity:"epic", image:"assets/cards/weapon_014.png" },
  { id:"weapon_015", name:"Dague des âmes", type:"weapon", cost:3, attack:2, durability:2, keywords:[], effects:[{ trigger:"onPlay", effect:"damage", target:"enemyCharacter", value:2 }], description:"Furie des vents.", rarity:"common", image:"assets/cards/weapon_015.png" },


  { id:"creature_055", name:"Acolyte du Filon Astral", type:"creature", cost:1, attack:1, health:3, keywords:[], effects:[{ trigger:"battlecry", effect:"gainEmptyManaCrystal", value:1 }], description:"Cri de guerre : gagne un cristal de mana vide.", rarity:"common", tribe:"human", image:"assets/cards/creature_055.png" },
  { id:"creature_056", name:"Écureuse des Étincelles", type:"creature", cost:2, attack:2, health:3, keywords:[], dynamicCost:"spellPlayedThisTurn", effects:[], description:"Coûte (1) de moins si vous avez joué un sort ce tour.", rarity:"common", tribe:"gnome", image:"assets/cards/creature_056.png" },
  { id:"creature_057", name:"Serviteur des Pièces Perdues", type:"creature", cost:3, attack:3, health:2, keywords:[], effects:[{ trigger:"deathrattle", effect:"addCardToHand", cardId:"token_004", count:1 }], description:"Râle d’agonie : ajoute une Pièce à votre main.", rarity:"common", tribe:"goblin", image:"assets/cards/creature_057.png" },
  { id:"creature_058", name:"Canaliseur du Zénith", type:"creature", cost:3, attack:3, health:4, keywords:[], effects:[{ trigger:"battlecry", effect:"gainManaCrystalIfEmpty", value:1 }], description:"Cri de guerre : si vous n’avez plus de mana, gagnez un cristal de mana.", rarity:"rare", tribe:"human", image:"assets/cards/creature_058.png" },
  { id:"creature_059", name:"Sculptrice d’Étoiles", type:"creature", cost:4, attack:4, health:4, keywords:[], dynamicCost:"cardsDrawn", effects:[], description:"Chaque fois que vous piochez une carte, coûte (1) de moins.", rarity:"rare", tribe:"human", image:"assets/cards/creature_059.png" },
  { id:"creature_060", name:"Géomancien de Saphir", type:"creature", cost:5, attack:4, health:5, keywords:[], effects:[{ trigger:"battlecry", effect:"nextSpellDiscount", value:2 }], description:"Cri de guerre : réduit de (2) le coût du prochain sort que vous jouez.", rarity:"rare", tribe:"human", image:"assets/cards/creature_060.png" },
  { id:"creature_061", name:"Oracle des Marées de Mana", type:"creature", cost:5, attack:4, health:6, keywords:[], effects:[{ trigger:"endOfTurn", effect:"gainEmptyManaIfCardsPlayed", threshold:2, value:1 }], description:"À la fin de votre tour, si vous avez joué 2 cartes ou plus, gagnez un cristal de mana vide.", rarity:"epic", tribe:"mystic", image:"assets/cards/creature_061.png" },
  { id:"creature_062", name:"Maëlia, Impératrice de l’Aube", type:"creature", cost:8, attack:7, health:8, keywords:[], effects:[{ trigger:"aura", effect:"minionCostAura", value:1 },{ trigger:"afterOwnerCreaturePlayed", effect:"gainEmptyManaCrystal", value:1 }], description:"Vos autres serviteurs coûtent (1) de moins. Chaque fois que vous jouez un serviteur, gagnez un cristal de mana vide.", rarity:"legendary", tribe:"human", image:"assets/cards/creature_062.png" },
  { id:"creature_063", name:"Gardien du Trône de Saphir", type:"creature", cost:6, attack:5, health:7, keywords:["taunt"], dynamicCost:"cardsPlayedThisTurn", effects:[], description:"Provocation. Coûte (1) de moins pour chaque carte jouée ce tour.", rarity:"epic", tribe:"construct", image:"assets/cards/creature_063.png" },
  { id:"creature_064", name:"Elysor, Architecte des Sources", type:"creature", cost:7, attack:6, health:8, keywords:[], dynamicCost:"friendlyBoardCount", effects:[{ trigger:"battlecry", effect:"refreshMana" }], description:"Cri de guerre : rafraîchit vos cristaux de mana. Coûte (1) de moins pour chaque serviteur allié.", rarity:"legendary", tribe:"human", image:"assets/cards/creature_064.png" },

  { id:"token_004", name:"La pièce", type:"spell", cost:0, keywords:[], effects:[{ trigger:"onPlay", effect:"gainTemporaryMana", value:1 }], description:"Gagnez 1 cristal de mana pour ce tour uniquement.", rarity:"rare", collectible:false, image:"assets/cards/token_004.png" },


  /* ======================================================================
     Nouvelles cartes — extension commune et rare V41
     Les cartes générées (jetons, Éclat de givre, Pièce instable et Hache)
     sont enregistrées mais ne sont pas ouvertes dans les paquets.
     ====================================================================== */
  { id:"new_veilleur_des_brumes", name:"Veilleur des Brumes", type:"creature", cost:3, attack:2, health:4, keywords:["taunt"], effects:[{ trigger:"deathrattle", effect:"areaDamage", target:"allEnemies", value:1 }], description:"Provocation. Râle d’agonie : inflige 1 point de dégâts à tous les ennemis.", rarity:"common", tribe:"spirit", image:"assets/cards/Veilleur_des_Brumes.png" },
  { id:"new_apprentie_du_flux", name:"Apprentie du Flux", type:"creature", cost:2, attack:2, health:3, keywords:[], effects:[{ trigger:"battlecry", effect:"returnToHand", target:"otherFriendlyCreature", discount:1 }], description:"Cri de guerre : renvoyez une autre carte alliée dans votre main. Elle coûte (1) cristal de moins.", rarity:"common", tribe:"human", image:"assets/cards/Apprentie_du_Flux.png" },
  { id:"new_braconnier_des_sables", name:"Braconnier des Sables", type:"creature", cost:4, attack:3, health:4, keywords:[], effects:[{ trigger:"battlecry", effect:"returnToHand", target:"enemyCreatureMaxCost", maxCost:3 }], description:"Cri de guerre : renvoie un serviteur adverse coûtant (3) cristaux ou moins dans la main de son propriétaire.", rarity:"common", tribe:"human", image:"assets/cards/Braconnier_des_Sables.png" },
  { id:"new_mineur_runique", name:"Mineur runique", type:"creature", cost:1, attack:1, health:2, keywords:[], effects:[{ trigger:"deathrattle", effect:"gainTemporaryMana", value:1 }], description:"Râle d’agonie : gagnez 1 cristal de mana temporaire ce tour-ci.", rarity:"common", tribe:"dwarf", image:"assets/cards/Mineur_runique.png" },
  { id:"new_sentinelle_du_hall", name:"Sentinelle du Hall", type:"creature", cost:5, attack:4, health:5, keywords:["taunt"], effects:[], description:"Provocation.", rarity:"common", tribe:"construct", image:"assets/cards/Sentinelle_du_Hall.png" },
  { id:"new_traqueuse_des_cometes", name:"Traqueuse des Comètes", type:"creature", cost:3, attack:3, health:2, keywords:[], effects:[{ trigger:"battlecry", effect:"damageEnemyHeroIfSpellPlayedThisTurn", value:2 }], description:"Cri de guerre : inflige 2 points de dégâts au héros adverse si vous avez lancé un sort ce tour-ci.", rarity:"common", tribe:"elf", image:"assets/cards/Traqueuse_des_Comètes.png" },
  { id:"new_archiviste_astrea", name:"Archiviste d'Astréa", type:"creature", cost:4, attack:2, health:5, keywords:[], effects:[{ trigger:"battlecry", effect:"drawAndDiscountIfType", cardType:"spell", draw:1, discount:1 }], description:"Cri de guerre : piochez une carte. Si c’est un sort, il coûte (1) cristal de moins.", rarity:"common", tribe:"human", image:"assets/cards/Archiviste_d'Astréa.png" },
  { id:"new_rejeton_des_cendres", name:"Rejeton des Cendres", type:"creature", cost:2, attack:3, health:1, keywords:[], effects:[{ trigger:"deathrattle", effect:"randomDamage", target:"randomEnemyCharacter", value:2, count:1 }], description:"Râle d’agonie : inflige 2 points de dégâts à un ennemi aléatoire.", rarity:"common", tribe:"demon", image:"assets/cards/Rejeton_des_Cendres.png" },
  { id:"new_gardienne_du_sceau", name:"Gardienne du Sceau", type:"creature", cost:6, attack:5, health:6, keywords:[], effects:[{ trigger:"battlecry", effect:"returnToHand", target:"otherFriendlyCreature", discount:2 }], description:"Cri de guerre : renvoyez un serviteur allié dans votre main. Il coûte (2) cristaux de moins.", rarity:"common", tribe:"human", image:"assets/cards/Gardienne_du_Sceau.png" },
  { id:"new_frondeur_du_crepuscule", name:"Frondeur du Crépuscule", type:"creature", cost:4, attack:4, health:3, keywords:[], effects:[{ trigger:"battlecry", effect:"areaDamage", target:"allCreatures", value:1 }], description:"Cri de guerre : inflige 1 point de dégâts à tous les serviteurs.", rarity:"common", tribe:"human", image:"assets/cards/Frondeur_du_Crépuscule.png" },
  { id:"new_dragon_de_scories", name:"Dragon de Scories", type:"creature", cost:4, attack:4, health:3, keywords:[], effects:[{ trigger:"battlecry", effect:"damageAllOtherMinions", value:1 }], description:"Cri de guerre : inflige 1 point de dégâts à tous les autres serviteurs.", rarity:"common", tribe:"dragon", image:"assets/cards/Dragon_de_Scories.png" },
  { id:"new_brute_de_ferroc", name:"Brute de Ferroc", type:"creature", cost:3, attack:3, health:4, keywords:["taunt"], effects:[], description:"Provocation.", rarity:"common", tribe:"orc", image:"assets/cards/Brute_de_Ferroc.png" },
  { id:"new_gobelin_bidouilleur", name:"Gobelin Bidouilleur", type:"creature", cost:2, attack:2, health:2, keywords:[], effects:[{ trigger:"battlecry", effect:"buffStats", target:"otherFriendlyCreature", attack:1, health:1 }], description:"Cri de guerre : donne +1/+1 à un autre serviteur allié.", rarity:"common", tribe:"goblin", image:"assets/cards/Gobelin_Bidouilleur.png" },
  { id:"new_lynx_des_ronces", name:"Lynx des Ronces", type:"creature", cost:1, attack:2, health:1, keywords:[], effects:[{ trigger:"battlecry", effect:"buffSelfIfOtherFriendly", attack:0, health:1 }], description:"Cri de guerre : gagne +1 PV si vous contrôlez un autre serviteur.", rarity:"common", tribe:"beast", image:"assets/cards/Lynx_des_Ronces.png" },
  { id:"new_automate_bastion", name:"Automate Bastion", type:"creature", cost:5, attack:3, health:6, keywords:["taunt"], effects:[], description:"Provocation.", rarity:"common", tribe:"mech", image:"assets/cards/Automate_Bastion.png" },
  { id:"new_drake_azure", name:"Drake azuré", type:"creature", cost:6, attack:5, health:6, keywords:[], effects:[{ trigger:"deathrattle", effect:"draw", target:"self", value:1 }], description:"Râle d’agonie : piochez une carte.", rarity:"common", tribe:"dragon", image:"assets/cards/Drake_azuré.png" },
  { id:"new_sanglier_de_loree", name:"Sanglier de l'Orée", type:"creature", cost:3, attack:3, health:2, keywords:["charge"], effects:[], description:"Charge.", rarity:"common", tribe:"beast", image:"assets/cards/Sanglier_de_l'Orée.png" },
  { id:"new_chaman_des_cendres", name:"Chaman des Cendres", type:"creature", cost:4, attack:3, health:5, keywords:[], effects:[{ trigger:"battlecry", effect:"damage", target:"enemyHero", value:2 }], description:"Cri de guerre : inflige 2 points de dégâts au héros adverse.", rarity:"common", tribe:"orc", image:"assets/cards/Chaman_des_Cendres.png" },
  { id:"new_recuperateur_a_ressorts", name:"Récupérateur à ressorts", type:"creature", cost:2, attack:1, health:4, keywords:[], effects:[{ trigger:"deathrattle", effect:"addRandomTribeToHand", tribe:"mech", count:1 }], description:"Râle d’agonie : ajoute un Méca aléatoire à votre main.", rarity:"common", tribe:"goblin", image:"assets/cards/Récupérateur_à_ressorts.png" },
  { id:"new_faucon_mecanique", name:"Faucon mécanique", type:"creature", cost:3, attack:2, health:4, keywords:[], effects:[{ trigger:"battlecry", effect:"drawIfControlTribe", tribe:"mech", value:1 }], description:"Cri de guerre : piochez une carte si vous contrôlez un Méca.", rarity:"common", tribe:"mech", image:"assets/cards/Faucon_mécanique.png" },

  { id:"new_tempete_runique", name:"Tempête runique", type:"spell", cost:3, keywords:[], effects:[{ trigger:"onPlay", effect:"areaDamageDrawIfDeath", target:"allCreatures", value:2, draw:1 }], description:"Inflige 2 points de dégâts à tous les serviteurs. Si l’un d’eux meurt, piochez une carte.", rarity:"rare", image:"assets/cards/Tempête_runique.png" },
  { id:"new_drake_du_givre_ancien", name:"Drake du Givre ancien", type:"creature", cost:5, attack:4, health:5, keywords:[], effects:[{ trigger:"battlecry", effect:"freeze", target:"anyCreature" },{ trigger:"deathrattle", effect:"addCardToHand", cardId:"generated_eclat_de_givre", count:1 }], description:"Cri de guerre : gèle un serviteur. Râle d’agonie : ajoute un Éclat de givre à votre main.", rarity:"rare", tribe:"dragon", image:"assets/cards/Drake_du_Givre_ancien.png" },
  { id:"new_chef_de_guerre_ferroc", name:"Chef de guerre Ferroc", type:"creature", cost:4, attack:4, health:4, keywords:[], effects:[{ trigger:"battlecry", effect:"buffAllFriendlyAttackThisTurn", value:2, excludeSelf:true }], description:"Cri de guerre : vos autres serviteurs gagnent +2 ATQ ce tour-ci.", rarity:"rare", tribe:"orc", image:"assets/cards/Chef_de_guerre_Ferroc.png" },
  { id:"new_bombardier_gobelin", name:"Bombardier Gobelin", type:"creature", cost:3, attack:3, health:3, keywords:[], effects:[{ trigger:"battlecry", effect:"damageAndDrawIfSurvives", target:"anyCharacter", value:2, draw:1 }], description:"Cri de guerre : inflige 2 points de dégâts. Si la cible survit, piochez une carte.", rarity:"rare", tribe:"goblin", image:"assets/cards/Bombardier_Gobelin.png" },
  { id:"new_canon_a_vapeur", name:"Canon à vapeur", type:"spell", cost:4, keywords:[], effects:[{ trigger:"onPlay", effect:"summon", target:"friendlyBoard", cardId:"token_meca_a_vapeur", count:1 }], description:"Invoque un Méca 2/3 avec Provocation.", rarity:"rare", image:"assets/cards/Canon_à_vapeur.png" },
  { id:"new_mastodonte_des_ronces", name:"Mastodonte des Ronces", type:"creature", cost:6, attack:5, health:6, keywords:[], effects:[{ trigger:"deathrattle", effect:"summon", target:"friendlyBoard", cardId:"token_marcassin", count:1 }], description:"Râle d’agonie : invoque un Marcassin 2/2.", rarity:"rare", tribe:"beast", image:"assets/cards/Mastodonte_des_Ronces.png" },
  { id:"new_totem_des_braises", name:"Totem des braises", type:"spell", cost:2, keywords:[], effects:[{ trigger:"onPlay", effect:"damage", target:"anyCreature", value:3 },{ trigger:"onPlay", effect:"conditionalDamageEnemyHeroIfTribe", tribe:"orc", value:1 }], description:"Inflige 3 points de dégâts à un serviteur. Si vous contrôlez un Orc, inflige 1 point de dégât au héros adverse.", rarity:"rare", image:"assets/cards/Totem_des_braises.png" },
  { id:"new_sentinelle_des_engrenages", name:"Sentinelle des engrenages", type:"creature", cost:5, attack:3, health:7, keywords:["taunt"], effects:[{ trigger:"endOfTurn", effect:"buffFriendlyTribe", tribe:"mech", attack:0, health:1, excludeSelf:true }], description:"Provocation. À la fin de votre tour, vos autres Méca gagnent +1 PV.", rarity:"rare", tribe:"mech", image:"assets/cards/Sentinelle_des_engrenages.png" },
  { id:"new_traqueuse_du_neant", name:"Traqueuse du Néant", type:"creature", cost:4, attack:5, health:2, keywords:[], effects:[{ trigger:"battlecry", effect:"returnToHand", target:"damagedCreature" }], description:"Cri de guerre : renvoie un serviteur blessé dans la main de son propriétaire.", rarity:"rare", tribe:"elf", image:"assets/cards/Traqueuse_du_Néant.png" },
  { id:"new_benediction_astrale", name:"Bénédiction astrale", type:"spell", cost:5, keywords:[], effects:[{ trigger:"onPlay", effect:"buffAllFriendly", target:"allFriendlyCreatures", value:2 },{ trigger:"onPlay", effect:"draw", target:"self", value:1 }], description:"Donne +2/+2 à tous vos serviteurs. Piochez une carte.", rarity:"rare", image:"assets/cards/Bénédiction_astrale.png" },
  { id:"generated_marcassin", name:"Marcassin", type:"token", cost:1, attack:2, health:2, keywords:[], effects:[], description:"Un jeune sanglier 2/2.", rarity:"common", tribe:"beast", collectible:false, image:"assets/cards/Marcassin.png" },
  { id:"generated_eclat_de_givre", name:"Éclat de givre", type:"spell", cost:1, keywords:[], effects:[{ trigger:"onPlay", effect:"freezeOrDamageIfFrozen", target:"anyCreature", value:2 }], description:"Gèle un serviteur. S’il est déjà gelé, inflige-lui 2 points de dégâts.", rarity:"rare", collectible:false, image:"assets/cards/Éclat_de_givre.png" },

  { id:"new_drake_des_braises_eternelles", name:"Drake des braises éternelles", type:"creature", cost:5, attack:5, health:4, keywords:[], effects:[{ trigger:"battlecry", effect:"damageAndSummonIfKilled", target:"anyCreature", value:2, cardId:"generated_dragonnet" }], description:"Cri de guerre : inflige 2 points de dégâts à un serviteur. S’il meurt, invoque un Dragonnet 2/1.", rarity:"rare", tribe:"dragon", image:"assets/cards/Drake_des_braises_éternelles.png" },
  { id:"new_chaman_brise_tempete", name:"Chaman brise-tempête", type:"creature", cost:4, attack:3, health:5, keywords:[], effects:[{ trigger:"battlecry", effect:"summon", target:"friendlyBoard", cardId:"generated_totem", count:1 },{ trigger:"battlecry", effect:"discountSpellsThisTurn", value:1 }], description:"Cri de guerre : invoque un Totem 0/2. Vos sorts coûtent (1) de moins ce tour-ci.", rarity:"rare", tribe:"orc", image:"assets/cards/Chaman_brise-tempête.png" },
  { id:"new_chef_de_siege_ferroc", name:"Chef de siège Ferroc", type:"creature", cost:4, attack:4, health:5, keywords:["taunt"], effects:[{ trigger:"battlecry", effect:"equipWeaponCard", cardId:"generated_hache" }], description:"Provocation. Cri de guerre : équipez une Hache 2/2.", rarity:"rare", tribe:"orc", image:"assets/cards/Chef_de_siège_Ferroc.png" },
  { id:"new_corrupteur_abyssal", name:"Corrupteur abyssal", type:"creature", cost:6, attack:6, health:5, keywords:[], effects:[{ trigger:"battlecry", effect:"discardRandom", count:1 },{ trigger:"battlecry", effect:"destroyIfDamaged", target:"damagedCreature" }], description:"Cri de guerre : défaussez une carte. Détruisez un serviteur blessé.", rarity:"rare", tribe:"demon", image:"assets/cards/Corrupteur_abyssal.png" },
  { id:"new_championne_de_laurore", name:"Championne de l'Aurore", type:"creature", cost:5, attack:4, health:6, keywords:["divineShield"], effects:[{ trigger:"battlecry", effect:"healAllFriendlyMinions", value:3 }], description:"Bouclier divin. Cri de guerre : rend 3 PV à tous vos serviteurs.", rarity:"rare", tribe:"human", image:"assets/cards/Championne_de_l'Aurore.png" },
  { id:"new_broyeur_a_pistons", name:"Broyeur à pistons", type:"creature", cost:5, attack:4, health:5, keywords:[], effects:[{ trigger:"deathrattle", effect:"addRandomTribeToHand", tribe:"mech", maxCost:4, count:1 }], description:"Râle d’agonie : ajoute un Méca aléatoire coûtant (4) ou moins à votre main.", rarity:"rare", tribe:"mech", image:"assets/cards/Broyeur_à_pistons.png" },
  { id:"new_artificier_fulminant", name:"Artificier fulminant", type:"creature", cost:3, attack:2, health:4, keywords:[], effects:[{ trigger:"battlecry", effect:"addCardToHand", cardId:"generated_piece_instable", count:1 }], description:"Cri de guerre : ajoute une Pièce instable à votre main. Elle inflige 1 point de dégât.", rarity:"rare", tribe:"goblin", image:"assets/cards/Artificier_fulminant.png" },
  { id:"new_alpha_des_crocs_dargent", name:"Alpha des crocs d'argent", type:"creature", cost:4, attack:4, health:3, keywords:[], effects:[{ trigger:"battlecry", effect:"buffFriendlyTribe", tribe:"beast", attack:1, health:1, excludeSelf:true }], description:"Cri de guerre : donne +1/+1 à vos autres Bêtes.", rarity:"rare", tribe:"beast", image:"assets/cards/Alpha_des_crocs_d'argent.png" },
  { id:"new_veteran_du_rempart", name:"Vétéran du rempart", type:"creature", cost:6, attack:3, health:8, keywords:["taunt"], effects:[{ trigger:"afterDamaged", effect:"gainTemporaryAttack", value:2 }], description:"Provocation. À chaque fois qu’il subit des dégâts, gagne +2 ATQ ce tour-ci.", rarity:"rare", tribe:"human", image:"assets/cards/Vétéran_du_rempart.png" },
  { id:"new_maree_purificatrice", name:"Marée purificatrice", type:"spell", cost:3, keywords:[], effects:[{ trigger:"onPlay", effect:"healAndSummonIfFullBefore", target:"friendlyCreature", value:4, cardId:"generated_totem" }], description:"Rend 4 PV à un serviteur. Invoque un Totem 0/2 s’il est déjà à tous ses PV.", rarity:"rare", image:"assets/cards/Marée_purificatrice.png" },
  { id:"generated_totem", name:"Totem", type:"token", cost:1, attack:0, health:2, keywords:[], effects:[], description:"Un Totem 0/2.", rarity:"common", tribe:"totem", collectible:false, image:"assets/cards/Totem.png" },
  { id:"generated_dragonnet", name:"Dragonnet", type:"token", cost:1, attack:2, health:1, keywords:[], effects:[], description:"Un jeune Dragonnet 2/1.", rarity:"common", tribe:"dragon", collectible:false, image:"assets/cards/Dragonnet.png" },
  { id:"generated_piece_instable", name:"Pièce instable", type:"spell", cost:1, keywords:[], effects:[{ trigger:"onPlay", effect:"damage", target:"enemyCharacter", value:1 }], description:"Inflige 1 point de dégât à un adversaire.", rarity:"common", collectible:false, image:"assets/cards/Pièce_instable.png" },
  { id:"generated_hache", name:"Hache", type:"weapon", cost:2, attack:2, durability:2, keywords:[], effects:[], description:"Une Hache 2/2.", rarity:"common", collectible:false, image:"assets/cards/Hache.png" },
  { id:"token_meca_a_vapeur", name:"Méca à vapeur", type:"token", cost:2, attack:2, health:3, keywords:["taunt"], effects:[], description:"Provocation.", rarity:"common", tribe:"mech", collectible:false, image:"assets/cards/Automate_Bastion.png" },

  /* Jetons, absents de la collection et des decks */
  { id:"token_001", name:"Agneau astral", type:"token", cost:1, attack:1, health:1, keywords:[], effects:[], description:"Une forme inoffensive née d’une métamorphose.", rarity:"common", tribe:"beast", collectible:false, image:"assets/cards/token_001.jpg" },
  { id:"token_002", name:"Fragment d’étoile", type:"token", cost:2, attack:2, health:2, keywords:[], effects:[], description:"Un éclat vivant du firmament.", rarity:"common", tribe:"elemental", collectible:false, image:"assets/cards/token_002.jpg" },
  { id:"token_003", name:"Loup spectral mineur", type:"token", cost:1, attack:1, health:1, keywords:[], effects:[], description:"Un écho spectral 1/1 revenu de l’au-delà.", rarity:"common", tribe:"beast", collectible:false, image:"assets/cards/token_003.png" }
];

const DEFAULT_PLAYER_DECK = [
  "quest_001","quest_002","creature_001","creature_001","creature_002","creature_002",
  "creature_003","creature_003","creature_005","creature_005","creature_006","creature_006",
  "creature_019","creature_019","creature_020","creature_020","creature_021","creature_021",
  "creature_022","creature_022","creature_023","creature_024","creature_025","spell_001",
  "spell_001","spell_006","spell_014","spell_015","weapon_003","secret_001"
];

const AI_DECK_LIST = [
  "creature_027","creature_027","creature_028","creature_028","creature_029","creature_029",
  "creature_030","creature_030","creature_031","creature_031","creature_032","creature_032",
  "creature_033","creature_034","creature_035","creature_036","creature_038","creature_039","creature_040",
  "location_001","weapon_004","spell_028","spell_028","spell_029","spell_030",
  "creature_043","creature_051","creature_054","weapon_009","spell_038"
];
